databases:
  - name: blood_alley_tours_api
    databaseName: blood_alley_tours_api
    user: blood_alley_tours_api

services:
  - type: web
    name: blood_alley_tours_api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blood_alley_tours_api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false